# Generated by Django 3.0.5 on 2020-04-11 09:36

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(blank=True, max_length=250, verbose_name='Email Address')),
                ('phone_num', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('pincode', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
