# Generated by Django 2.2.12 on 2020-04-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19dashboardapi', '0003_userconv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userconv',
        ),
    ]
