# Generated by Django 2.2.12 on 2020-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19dashboardapi', '0004_delete_userconv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emailAddress',
            field=models.EmailField(max_length=250, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
